version: 2

jobs:
  autogen_build:
    docker:
      - image: dbohdan1/circleci-tcl-gcc-autoconf:0.3.0.27-master
    steps:
      - checkout
      - run: ./autogen.sh
      - run: ./configure
      - run: make test
  committed_configure_build:
    docker:
      - image: dbohdan1/circleci-tcl-gcc-autoconf:0.3.0.27-master
    steps:
      - checkout
      - run: ./configure
      - run: make test

workflows:
  version: 2
  build_all:
    jobs:
      - autogen_build
      - committed_configure_build
